# Copyright (c) 2025 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# Platform configuration file for Samsung Exynos 9820 devices (exynos9820)
# Ported from ExtremeROM (beyond / Galaxy S10 5G) for One UI 9 / Android 17.
TARGET_BOARD_API_LEVEL=31
TARGET_PRODUCT_SHIPPING_API_LEVEL=28

# Static partitions (Galaxy S10 5G does NOT use dynamic partitions)
TARGET_USE_DYNAMIC_PARTITIONS=false
TARGET_SUPER_GROUP_NAME="none"

# TODO: fill from device: `adb shell cat /proc/partitions` / `lpdump` of S10 5G (beyondx)
TARGET_SYSTEM_PARTITION_SIZE=0
TARGET_VENDOR_PARTITION_SIZE=0
TARGET_PRODUCT_PARTITION_SIZE=0
TARGET_ODM_PARTITION_SIZE=0
TARGET_VENDOR_DLKM_PARTITION_SIZE=0
TARGET_ODM_DLKM_PARTITION_SIZE=0
TARGET_SYSTEM_DLKM_PARTITION_SIZE=0

TARGET_BOOT_PARTITION_SIZE=0
TARGET_DTBO_PARTITION_SIZE=0
TARGET_VENDOR_BOOT_PARTITION_SIZE=0
TARGET_CACHE_PARTITION_SIZE=0
TARGET_RECOVERY_PARTITION_SIZE=0

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="essi"
TARGET_OS_FILE_SYSTEM_TYPE="erofs"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false